name: GameEngine
version: '1.0.0'
main: me.fbiflow.remapped.BukkitLoader
api-version: '1.20'
commands:
  game-engine:
    aliases: [game]
    usage: "game-engine <play/party>"
    permission: game-engine.player
    permission-message: "you don`t have permission to perform this command"